Update test_gpu.yml

diff --git a/.github/workflows/test_gpu.yml b/.github/workflows/test_gpu.yml
--- a/.github/workflows/test_gpu.yml
+++ b/.github/workflows/test_gpu.yml
@@ -46,6 +46,13 @@ jobs:
           AK: ${{ secrets.BOS_AK }}
           SK: ${{ secrets.BOS_SK }}
         run: |
+          if [ -z "$AK" ] || [ -z "$SK" ]; then
+            echo "Error: AK or SK is not set."
+            exit 1
+          else
+            echo "AK and SK are set."
+          fi
+
           python -m pip install bce-python-sdk==0.8.74
           wget -q --no-proxy https://xly-devops.bj.bcebos.com/home/bos_new.tar.gz
           tar xf bos_new.tar.gz
